---
title: "ESM 244 Lab Week 2"
author: "Sydney Rilum"
date: "1/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(palmerpenguins)

# For PCA:
library(ggfortify)

# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguins_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>%  # keeps variables in mm units
  drop_na() %>% 
  scale() %>%  # values scaled
  prcomp() # makes data frame into a list of info

penguins_pca$rotation  # brings up loadings for each variables

# Create a dataset that drops NAs but contains all 8 variables to add aesthetics to biplot, matches PCA dataset
penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

# Create a biplot using autoplot (from ggfortify)
autoplot(penguins_pca,
         data = penguin_complete,
         colour = 'species',
         loadings = TRUE,
         loadings.label = TRUE) + # shows loadings of each variable
  theme_minimal() # can customize just like ggplot
```









